apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-cron
  labels:
    app: backend-cron
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-cron
  template:
    metadata:
      labels:
        app: backend-cron
    spec:
      containers:
        - name: backend-cron
          image: abc.docker-registry.gewis.nl/pos/sudosos/backend:latest
          imagePullPolicy: Always
          command: ["/app/init_scripts/start-cron.sh"]
          livenessProbe:
            exec:
              command: ["sh", "-c", "kill -0 1"]
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          envFrom:
            - configMapRef:
                name: backend-env-config
            - secretRef:
                name: backend-env
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
      dnsConfig:
        options:
          - name: ndots
            value: '1'
