apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: abc.docker-registry.gewis.nl/pos/sudosos/backend:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
            - name: ws
              containerPort: 8080
          startupProbe:
            httpGet:
              path: /v1/ping
              port: http
            periodSeconds: 5
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /v1/ping
              port: http
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /v1/ping
              port: http
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          envFrom:
            - configMapRef:
                name: backend-env-config
            - secretRef:
                name: backend-env
          volumeMounts:
            - name: jwt-key
              mountPath: /app/config/jwt.key
              subPath: jwt.key
              readOnly: true
            - name: data
              mountPath: /app/data
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      dnsConfig:
        options:
          - name: ndots
            value: '1'
      volumes:
        - name: jwt-key
          secret:
            secretName: backend-jwt
            items:
              - key: JWT_PRIVATE_KEY
                path: jwt.key
        - name: data
          persistentVolumeClaim:
            claimName: sudosos-data
