image: node:14
stages:
- install
- build
- test

cache:
  paths:
  - node_modules/

install_dependencies:
  stage: install
  script: npm install
  artifacts:
    paths:
    - node_modules/

build:
  stage: build
  script: npm run build
  artifacts:
    paths:
    - out/

swagger:
  stage: build
  script: npm run swagger
  artifacts:
    paths:
    - out/

dockerize-master:
  image: docker:19.03
  stage: build
  services:
    - docker:19.03-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

dockerize:
  image: docker:19.03
  stage: build
  services:
    - docker:19.03-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master

test:
  stage: test
  before_script:
    - openssl genrsa -out config/jwt.key 2048
  script: npm run coverage
  artifacts:
    paths:
    - reports/coverage/

lint:
  stage: test
  script: npm run lint
