FROM node:20-alpine AS typedoc-builder

WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY ./ ./
COPY tsconfig.json ./

RUN yarn typedoc

FROM node:20-alpine AS vitepress-builder

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY ./docs/ ./docs
COPY --from=typedoc-builder /app/docs/content/typedoc/ ./docs/content/typedoc/

RUN yarn docs:build

FROM nginx:stable-alpine AS final-stage

RUN rm /etc/nginx/conf.d/default.conf
COPY docs/nginx.conf /etc/nginx/conf.d/default.conf

WORKDIR /app
COPY --from=vitepress-builder /app/docs/.vitepress/dist /app

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
