FROM node:20-alpine AS typedoc-builder

RUN npm install -g pnpm@10.33.0

WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY ./ ./
COPY tsconfig.json ./

RUN pnpm typedoc

FROM node:20-alpine AS vitepress-builder

RUN npm install -g pnpm@10.33.0

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY ./docs/ ./docs
COPY --from=typedoc-builder /app/docs/content/typedoc/ ./docs/content/typedoc/

RUN pnpm docs:build

FROM nginx:stable-alpine AS final-stage

RUN rm /etc/nginx/conf.d/default.conf
COPY docs/nginx.conf /etc/nginx/conf.d/default.conf

WORKDIR /app
COPY --from=vitepress-builder /app/docs/.vitepress/dist /app

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
