apiVersion: apps/v1
kind: Deployment
metadata:
  name: pos
  labels:
    app: pos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pos
  template:
    metadata:
      labels:
        app: pos
    spec:
      containers:
        - name: pos
          image: abc.docker-registry.gewis.nl/pos/sudosos/point-of-sale:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
