apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: data-products
              mountPath: /data/products
            - name: data-banners
              mountPath: /data/banners
            - name: data-invoices
              mountPath: /data/invoices
            - name: data-payout-requests
              mountPath: /data/payout_requests
            - name: data-seller-payouts
              mountPath: /data/seller_payouts
            - name: data-write-offs
              mountPath: /data/write_offs
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: data-products
          persistentVolumeClaim:
            claimName: sudosos-products
        - name: data-banners
          persistentVolumeClaim:
            claimName: sudosos-banners
        - name: data-invoices
          persistentVolumeClaim:
            claimName: sudosos-invoices
        - name: data-payout-requests
          persistentVolumeClaim:
            claimName: sudosos-payout-requests
        - name: data-seller-payouts
          persistentVolumeClaim:
            claimName: sudosos-seller-payouts
        - name: data-write-offs
          persistentVolumeClaim:
            claimName: sudosos-write-offs
