apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-beta
  labels:
    app: frontend-beta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-beta
  template:
    metadata:
      labels:
        app: frontend-beta
    spec:
      containers:
        - name: frontend-beta
          image: abc.docker-registry.gewis.nl/pos/sudosos/dashboard:develop
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
