apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - sealed-backend-env.yaml
  - traefik/ingressroute.yaml

patches:
  - path: patches/backend-config.yaml

# Image tags for production — pinned to release versions
images:
  - name: abc.docker-registry.gewis.nl/pos/sudosos/backend
    newTag: "1.29.0"
  - name: abc.docker-registry.gewis.nl/pos/sudosos/dashboard
    newTag: "1.43.0"
  - name: abc.docker-registry.gewis.nl/pos/sudosos/point-of-sale
    newTag: "1.43.0"
  - name: abc.docker-registry.gewis.nl/pos/sudosos/docs
    newTag: develop
  - name: abc.docker-registry.gewis.nl/eou/pdf-generator
    newTag: "1.5.1"
