apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pvcs.yaml
  # nginx
  - nginx/configmap.yaml
  - nginx/deployment.yaml
  - nginx/service.yaml
  - nginx/ingress.yaml
  # backend
  - backend/configmap.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  # frontend
  - frontend/deployment.yaml
  - frontend/service.yaml
  - frontend-beta/deployment.yaml
  - frontend-beta/service.yaml
  # point of sale
  - pos/deployment.yaml
  - pos/service.yaml
  - pos-develop/deployment.yaml
  - pos-develop/service.yaml
  # docs
  - docs/deployment.yaml
  - docs/service.yaml
  # pdf
  - pdf/deployment.yaml
  - pdf/service.yaml
  - pdf/configmap.yaml
  - pdf-compiler/deployment.yaml
  - pdf-compiler/service.yaml
  # redis
  - redis/statefulset.yaml
  - redis/service.yaml
