name: Docker Build & Push

on:
  push:
    branches: [ main, develop ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
  dockerize:
    runs-on: ubuntu-latest
    container:
      image: docker:dind
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get Docker meta (for tags)
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_TAG }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Registry (GitHub)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Container Registry
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ghcr.io/gewis/${{ vars.DOCKER_TAG }}:${{ steps.meta.outputs.version }}
          cache-from: type=gha

      - name: Login to SudoSOS Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.SVC_GH_SUDOSOS_USERNAME }}
          password: ${{ secrets.SVC_GH_SUDOSOS_PWD }}

      # Build and push Docker image with Buildx (don't push on PR)
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64 #SudoSOS does not run on linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
