name: Docker

on:
  workflow_dispatch:
  push:
    branches: [develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dockerize:
    permissions:
      contents: read
      packages: write
    uses: GEWIS/actions/.github/workflows/docker-branch-release.yml@v1
    with:
      projects: '["."]'
      docker-paths: '["${{ vars.DOCKER_TAG }}"]'
      github-registry: 'true'
