name: Docs

on:
  push:
    branches:
      - main
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dockerize:
    permissions:
      contents: read
      packages: write
    uses: GEWIS/actions/.github/workflows/docker-branch-release.yml@v1
    with:
      projects: '["."]'
      docker-paths: '["${{ vars.DOCKER_DOCS_TAG }}"]'
      docker-registry: ${{ vars.DOCKER_REGISTRY }}
      dockerfile: './Dockerfile-docs'
    secrets:
      REGISTRY_USERNAME: ${{ secrets.SVC_GH_SUDOSOS_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.SVC_GH_SUDOSOS_PWD }}
