name: Prepare Release PR

on:
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  create-release-pr:
    permissions:
      contents: read
      pull-requests: write
    uses: GEWIS/actions/.github/workflows/prepare-release-pr.yml@v1
