name: Trigger Client Update

on:
  push:
    branches:
      - main
      - develop

jobs:
  dispatchClientUpdate:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.SUDOSOS_APP_TOKEN }}
          repository: GEWIS/sudosos-client
          event-type: backend-update
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
