apiVersion: apps/v1
kind: Deployment
metadata:
  name: static
  labels:
    app: static
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static
  template:
    metadata:
      labels:
        app: static
    spec:
      containers:
        - name: static
          image: caddy:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: static-config
              mountPath: /etc/caddy/Caddyfile
              subPath: Caddyfile
            - name: data-products
              mountPath: /srv/static/products
            - name: data-banners
              mountPath: /srv/static/banners
            - name: data-invoices
              mountPath: /srv/static/invoices
            - name: data-payout-requests
              mountPath: /srv/static/payouts
            - name: data-seller-payouts
              mountPath: /srv/static/sellerPayouts
            - name: data-write-offs
              mountPath: /srv/static/writeOffs
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
      volumes:
        - name: static-config
          configMap:
            name: static-config
        - name: data-products
          persistentVolumeClaim:
            claimName: sudosos-products
        - name: data-banners
          persistentVolumeClaim:
            claimName: sudosos-banners
        - name: data-invoices
          persistentVolumeClaim:
            claimName: sudosos-invoices
        - name: data-payout-requests
          persistentVolumeClaim:
            claimName: sudosos-payout-requests
        - name: data-seller-payouts
          persistentVolumeClaim:
            claimName: sudosos-seller-payouts
        - name: data-write-offs
          persistentVolumeClaim:
            claimName: sudosos-write-offs
